-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "Permission" ADD VALUE 'ADD_MACHINE_CHECKLIST';
ALTER TYPE "Permission" ADD VALUE 'EDIT_MACHINE_CHECKLIST';
ALTER TYPE "Permission" ADD VALUE 'DELETE_MACHINE_CHECKLIST';
ALTER TYPE "Permission" ADD VALUE 'ADD_MACHINE_PERIODIC_MAINTENANCE';
ALTER TYPE "Permission" ADD VALUE 'EDIT_MACHINE_PERIODIC_MAINTENANCE';
ALTER TYPE "Permission" ADD VALUE 'DELETE_MACHINE_PERIODIC_MAINTENANCE';
ALTER TYPE "Permission" ADD VALUE 'ADD_MACHINE_SPARE_PR';
ALTER TYPE "Permission" ADD VALUE 'EDIT_MACHINE_SPARE_PR';
ALTER TYPE "Permission" ADD VALUE 'DELETE_MACHINE_SPARE_PR';
ALTER TYPE "Permission" ADD VALUE 'ADD_MACHINE_REPAIR';
ALTER TYPE "Permission" ADD VALUE 'EDIT_MACHINE_REPAIR';
ALTER TYPE "Permission" ADD VALUE 'DELETE_MACHINE_REPAIR';
ALTER TYPE "Permission" ADD VALUE 'ADD_MACHINE_BREAKDOWN';
ALTER TYPE "Permission" ADD VALUE 'EDIT_MACHINE_BREAKDOWN';
ALTER TYPE "Permission" ADD VALUE 'DELETE_MACHINE_BREAKDOWN';
ALTER TYPE "Permission" ADD VALUE 'ADD_MACHINE_ATTACHMENT';
ALTER TYPE "Permission" ADD VALUE 'EDIT_MACHINE_ATTACHMENT';
ALTER TYPE "Permission" ADD VALUE 'DELETE_MACHINE_ATTACHMENT';
ALTER TYPE "Permission" ADD VALUE 'ASSIGN_USER_TO_MACHINE';
ALTER TYPE "Permission" ADD VALUE 'UNASSIGN_USER_TO_MACHINE';
ALTER TYPE "Permission" ADD VALUE 'ADD_TRANSPORTATION_CHECKLIST';
ALTER TYPE "Permission" ADD VALUE 'EDIT_TRANSPORTATION_CHECKLIST';
ALTER TYPE "Permission" ADD VALUE 'DELETE_TRANSPORTATION_CHECKLIST';
ALTER TYPE "Permission" ADD VALUE 'ADD_TRANSPORTATION_PERIODIC_MAINTENANCE';
ALTER TYPE "Permission" ADD VALUE 'EDIT_TRANSPORTATION_PERIODIC_MAINTENANCE';
ALTER TYPE "Permission" ADD VALUE 'DELETE_TRANSPORTATION_PERIODIC_MAINTENANCE';
ALTER TYPE "Permission" ADD VALUE 'ADD_TRANSPORTATION_SPARE_PR';
ALTER TYPE "Permission" ADD VALUE 'EDIT_TRANSPORTATION_SPARE_PR';
ALTER TYPE "Permission" ADD VALUE 'DELETE_TRANSPORTATION_SPARE_PR';
ALTER TYPE "Permission" ADD VALUE 'ADD_TRANSPORTATION_REPAIR';
ALTER TYPE "Permission" ADD VALUE 'EDIT_TRANSPORTATION_REPAIR';
ALTER TYPE "Permission" ADD VALUE 'DELETE_TRANSPORTATION_REPAIR';
ALTER TYPE "Permission" ADD VALUE 'ADD_TRANSPORTATION_BREAKDOWN';
ALTER TYPE "Permission" ADD VALUE 'EDIT_TRANSPORTATION_BREAKDOWN';
ALTER TYPE "Permission" ADD VALUE 'DELETE_TRANSPORTATION_BREAKDOWN';
ALTER TYPE "Permission" ADD VALUE 'ADD_TRANSPORTATION_ATTACHMENT';
ALTER TYPE "Permission" ADD VALUE 'EDIT_TRANSPORTATION_ATTACHMENT';
ALTER TYPE "Permission" ADD VALUE 'DELETE_TRANSPORTATION_ATTACHMENT';
ALTER TYPE "Permission" ADD VALUE 'ASSIGN_USER_TO_TRANSPORTATION';
ALTER TYPE "Permission" ADD VALUE 'UNASSIGN_USER_TO_TRANSPORTATION';
