import { Field, ObjectType } from '@nestjs/graphql';
import { EntityAssignment } from 'src/assignment/entities/entity-assign.model';
import { Breakdown } from 'src/breakdown/entities/breakdown.entity';
import { Location } from 'src/location/entities/location.entity';
import { BaseModel } from 'src/models/base.model';
import { ChecklistItem } from 'src/models/checklist-item.model';
import { User } from 'src/models/user.model';
import { PeriodicMaintenance } from 'src/periodic-maintenance/dto/models/periodic-maintenance.model';
import { Type } from 'src/type/entities/type.entity';
import { EntityHistory } from './entity-history.model';
import { EntityPeriodicMaintenance } from './entity-periodic-maintenance.model';
import { SparePr } from 'src/spare-pr/entities/spare-pr.entity';
import { Repair } from 'src/repair/entities/repair.entity';
import { Division } from 'src/division/entities/division.entity';
import { HullType } from 'src/hull-type/entities/hull-type.entity';
import { GraphQLFloat } from 'graphql';
import { Brand } from 'src/brand/entities/brand.entity';
import { Engine } from 'src/engine/entities/engine.entity';

@ObjectType()
export class Entity extends BaseModel {
  createdBy?: User;
  type?: Type;
  machineNumber?: string;
  registeredDate?: Date;
  model?: string;
  zone?: string;
  location?: Location;
  division?: Division;
  engine?: Engine;
  currentRunning?: number;
  lastService?: number;
  interService?: number;
  measurement?: string;
  brand?: Brand;
  deletedAt?: Date;
  status?: string;
  note?: string;
  @Field(() => GraphQLFloat)
  dimension?: typeof GraphQLFloat;
  registryNumber?: string;
  transit?: boolean;
  capacity?: string;
  identificationNumber?: string;
  faCode?: string;
  lastServiceUpdateAt?: Date;
  currentRunningUpdateAt?: Date;
  hullType?: HullType;
  statusChangedAt?: Date;
  assignees?: EntityAssignment[];
  checklistItems?: ChecklistItem[];
  repairs?: Repair[];
  breakdowns?: Breakdown[];
  sparePRs?: SparePr[];
  histories?: EntityHistory[];
  periodicMaintenances?: PeriodicMaintenance[];
  parentEntityId?: number;
  subEntities?: Entity[];
  parentEntity?: Entity;
}
