-- AlterTable
ALTER TABLE "MachineHistory" ALTER COLUMN "breakdownHour" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "idleHour" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "workingHour" SET DATA TYPE DOUBLE PRECISION;
