import { registerEnumType } from '@nestjs/graphql';

export enum PermissionEnum {
  ADD_ROLE = 'ADD_ROLE',
  EDIT_ROLE = 'EDIT_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',
  ADD_PERMISSION = 'ADD_PERMISSION',
  EDIT_PERMISSION = 'EDIT_PERMISSION',
  DELETE_PERMISSION = 'DELETE_PERMISSION',
  ADD_MACHINE = 'ADD_MACHINE',
  EDIT_MACHINE = 'EDIT_MACHINE',
  DELETE_MACHINE = 'DELETE_MACHINE',
  ADD_TRANSPORTATION = 'ADD_TRANSPORTATION',
  EDIT_TRANSPORTATION = 'EDIT_TRANSPORTATION',
  DELETE_TRANSPORTATION = 'DELETE_TRANSPORTATION',
}

registerEnumType(PermissionEnum, {
  name: 'Permission',
  description: 'All permissions.',
});
